draw_text(10,10,("Postition: " + string(obj_player.x) + "," + string(obj_player.y) +"\n" + "Veloctiy: " + string(obj_player.velocityX) + "," + string(obj_player.velocityY)
+ "\nCan Jump: " + string(obj_player.canJump)
+ "Can Move: " + string(obj_player.canMove)
+ " \nIs Falling: " + string(obj_player.isFalling)
+ " Is Jumping: " + string(obj_player.isJumping)
+ " Jump Height: " + string(obj_player.jumpHeight)
+ " In Air: " + string(obj_player.inAir)
+ " On Ground: " + string(obj_player.onGround)
+ " \nCan Attack: " + string(obj_player.canAttack)
+ " Is Attacking: " + string(obj_player.isAttacking)
+ " \nCan Block: " + string(obj_player.canBlock)
+ " Is Blocking: " + string(obj_player.isBlocking)
+ " \nCan Evade: " + string(obj_player.canEvade)
+ " Is Evading: " + string(obj_player.isEvading)
+ " \nCan Dash: " + string(obj_player.canDash)
+ " Is Charging: " + string(obj_player.isCharging)
+ " Is Dashing: " + string(obj_player.isDashing)
+ " Charge Amount: " + string(obj_player.dashCharge)
+ " \nPlayer Direction: " + string(obj_player.playerDirection)));

draw_healthbar(healthBarX, healthBarY, (healthBarX + healthBarWidth), (healthBarY + healthBarHeight),
health, c_black, c_red, c_green, 3, true, false)