draw_text(10,10,("Postition: " + string(obj_player.x) + "," + string(obj_player.y) +"\n" + "Veloctiy: " + string(obj_player.velocityX) + "," + string(obj_player.velocityY)
+ "\nCnJmp: " + string(obj_player.canJump)
+ "CnMv: " + string(obj_player.canMove)
+ " \nIsFlling: " + string(obj_player.isFalling)
+ " IsJmpng: " + string(obj_player.isJumping)
+ " InAr: " + string(obj_player.inAir)
+ " OnGnd: " + string(obj_player.onGround)
+ " \nCnAtk: " + string(obj_player.canAttack)
+ " IsAtkng: " + string(obj_player.isAttacking)
+ " \nCnBlk: " + string(obj_player.canBlock)
+ " IsBlkng: " + string(obj_player.isBlocking)
+ " \nCnEvd: " + string(obj_player.canEvade)
+ " IsEvdng: " + string(obj_player.isEvading)
+ " \nCnDsh: " + string(obj_player.canDash)
+ " IsChrgng: " + string(obj_player.isCharging)
+ " IsDshng: " + string(obj_player.isDashing)
+ " ChrgAmnt: " + string(obj_player.dashCharge)
+ " \nPlrDir: " + string(obj_player.playerDirection)));

draw_healthbar(healthBarX, healthBarY, (healthBarX + healthBarWidth), (healthBarY + healthBarHeight),
health, c_black, c_red, c_green, 3, true, false)